<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Agregar Órdenes de Compra</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>

  <div class="container mt-5">
    <h3>Agregar Órdenes de Compra</h3>

    <form class="mb-3" action="addOrdenCompra" method="post" enctype="multipart/form-data">
      <div class="mb-3">
        <label for="nombre" class="form-label">Nombre:</label>
        <input type="text" id="nombre" name="nombre" class="form-control" placeholder="Nombre" required>
      </div>

      <div class="mb-3">
        <label for="apellido" class="form-label">Apellido:</label>
        <input type="text" id="apellido" name="apellido" class="form-control" placeholder="Apellido" required>
      </div>

      <div class="mb-3">
        <label for="nombre_producto" class="form-label">Nombre del Producto:</label>
        <input type="text" id="nombre_producto" name="nombre_producto" class="form-control" placeholder="Nombre del Producto" required>
      </div>

      <div class="mb-3">
        <label for="tipoDeProducto" class="form-label">Tipo del Producto:</label>
        <select name="tipoDeProducto" id="tipoDeProducto" class="form-select">
          <?php foreach ($categorias as $cat) {  ?>
            <option value="<?php echo $cat["id"]?>"><?php echo $cat["TipoProducto"]?></option>
          <?php } ?>
        </select>
      </div>

      <div class="mb-3">
        <label for="descripcion" class="form-label">Descripción:</label>
        <textarea id="descripcion" name="descripcion" class="form-control" placeholder="Descripción" required></textarea>
      </div>

      <div class="mb-3">
        <label for="imagen" class="form-label">Subir Imagen:</label>
        <input type="file" name="input_name" id="imagen" class="form-control" accept="image/*">
      </div>

      <div class="mb-3">
        <label for="fecha" class="form-label">Selecciona una fecha:</label>
        <input type="date" id="fecha" name="fecha" class="form-control">
      </div>

      <button type="submit" class="btn btn-primary">Enviar Orden</button>
    </form>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>