<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Distribuidora</title>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>

  <!-- Header -->
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="#">Trabajo Web2 LIBRE 2025</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
           
            <?php if (!$this->res->user) { ?>
              <li class="nav-item"><a class="btn btn-primary btn-sm" href="<?= BASE_URL ?>showLogin">Iniciar Sesión</a></li>
            <?php } ?>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <!-- Contenido Principal -->
  <div class="container mt-4">
    <div class="card text-center">
      <div class="card-body">
        <h5 class="card-title">Distribuidora de Productos Comerciables</h5>

      </div>
    </div>
  </div>

  